"""initial schema

Revision ID: 3e7745dce2ac
Revises: 
Create Date: 2026-09-23 10:58:24.407322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7745dce2ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('organization_email', sa.String(length=320), nullable=False),
    sa.Column('organization_phone', sa.String(length=15), nullable=False),
    sa.Column('organization_hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_organization_email'), 'organization', ['organization_email'], unique=True)
    op.create_table('admin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_name', sa.String(length=255), nullable=False),
    sa.Column('admin_email', sa.String(length=320), nullable=False),
    sa.Column('admin_phone', sa.String(length=15), nullable=False),
    sa.Column('admin_hashed_password', sa.String(length=255), nullable=False),
    sa.Column('admin_employee_id', sa.String(length=50), nullable=False),
    sa.Column('admin_organization_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_phone')
    )
    op.create_index(op.f('ix_admin_admin_email'), 'admin', ['admin_email'], unique=True)
    op.create_index(op.f('ix_admin_admin_organization_id'), 'admin', ['admin_organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_admin_organization_id'), table_name='admin')
    op.drop_index(op.f('ix_admin_admin_email'), table_name='admin')
    op.drop_table('admin')
    op.drop_index(op.f('ix_organization_organization_email'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
