"""fixed the admin and organization bug

Revision ID: d6ef470a1a17
Revises: bd1c36f6aafb
Create Date: 2026-09-23 11:14:37.860855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ef470a1a17'
down_revision: Union[str, Sequence[str], None] = 'bd1c36f6aafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
